### ISSUE TITLE
ShadowLands:    attempt to call global 'GetCurrencyInfo' (a nil value) 

### ISSUE THREAD

**Issue by yoshimo** [wow-addon/Broker_CurrencyFlow#1]
```
Message: ...e\AddOns\Broker_Currencyflow\Broker_Currencyflow.lua line 1095:
   attempt to call global 'GetCurrencyInfo' (a nil value)

```

**Comment by davidcraig** [comment]
current API for reference: https://wowwiki.fandom.com/wiki/API_GetCurrencyInfo

Possibilities, blizzard is renaming and it hasn't been updated yet, blizzard hasn't enabled full api on beta.

Sadly I do not yet have beta so I can't do anything other than look at resources for API's but cannot see anything in regards to currency at the minute, will keep an eye on this as beta progresses (and hopefully I get invited at some point :))

**Comment by yoshimo** [comment]
from https://github.com/ebonyfaye/9.0-Interface/blob/1899ab848ae624b7f10a52302cc66dee0e503b11/interface/addons/blizzard_apidocumentation/currencyinfodocumentation.lua
Maybe better?

**Comment by davidcraig** [comment]
Ah ok, so perhaps `GetCurrencyInfo(index)` needs to be C_CurrencyInfo.GetCurrencyInfo(index) - can you give this a try?

**Comment by yoshimo** [comment]
Isn't that simple

```
Message: ...e\AddOns\Broker_Currencyflow\Broker_Currencyflow.lua line 803:
   bad argument #2 to 'format' (string expected, got table)
```

**Comment by agentschmitt** [comment]
the return value has also changed, instead of multiple values you get an object.
see: https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#c_currencyinfogetcurrencyinfotype
and https://www.townlong-yak.com/framexml/beta/Blizzard_APIDocumentation#C_CurrencyInfo.GetCurrencyInfo

**Comment by davidcraig** [comment]
@agentschmitt thanks for that code, looks like it's working like a charm finally managed to test this on PTR - please check out that branch and have a play, the icons don't work yet, but as far as I can tell basic functionality now works.

**Comment by davidcraig** [comment]
Icons work now, additionally have added the new currencies in preparation for prepatch.

**Comment by agentschmitt** [comment]
For me the 9.0 branch works on beta client. Can see gold of my characters again without lua errors.
But had to download it from git. i also tried to install alpha by client but this had lua errors for me.

**Comment by davidcraig** [comment]
Yes this is currently not ready for release until 9.0 ships as shipping now would probably break the 8.x client, it will be released for curse on launch day ready for Shadowlands release
