### ISSUE TITLE
CurrecyFlow tooltip not working in 9.1.5

### ISSUE THREAD

**Issue by Zepher01** [wow-addon/Broker_CurrencyFlow#16]
As of patch 9.1.5 the tooltip display that shows all of the various currency data no longer displays.

**Comment by davidcraig** [comment]
Which broker display addon are you using, I have only ever used Bazooka and addon works in this.

**Comment by Zepher01** [comment]
Bazooka, it seems to have fixed itself on its own somehow.  Didn't work for a week or so and then one day it worked fine again.
-------- Original message --------From: David Craig ***@***.***> Date: 2021-11-24  2:30 p.m.  (GMT-05:00) To: wow-addon/Broker_CurrencyFlow ***@***.***> Cc: Zepher01 ***@***.***>, Author ***@***.***> Subject: Re: [wow-addon/Broker_CurrencyFlow] CurrecyFlow tooltip not working in 9.1.5 (Issue #16) 
Which broker display addon are you using, I have only ever used Bazooka and addon works in this.

**Comment by davidcraig** [comment]
As long as it's working now 👍🏻 will close this issue :)

**Comment by Zepher01** [comment]
Thank you for looking after it!  BTW I LOVE the addon!
-------- Original message --------From: David Craig ***@***.***> Date: 2021-11-24  6:26 p.m.  (GMT-05:00) To: wow-addon/Broker_CurrencyFlow ***@***.***> Cc: Zepher01 ***@***.***>, Author ***@***.***> Subject: Re: [wow-addon/Broker_CurrencyFlow] CurrecyFlow tooltip not working in 9.1.5 (Issue #16) 

As long as it's working now 👍🏻 will close this issue :)

**Comment by davidcraig** [comment]
No problem, I love the addon too, just not the game anymore :)
