### ISSUE TITLE
Request: Add these currencies please.

### ISSUE THREAD

**Issue by Loredrin** [wow-addon/Broker_CurrencyFlow#17]
Could the following currencies be added, please?

- Valor
- Soul Cinders
- Stygian Ember
- Grateful Offering
- Cataloged Research
- Tower Knowledge
- Redeemed Soul

Thank you!

**Comment by yoshimo** [comment]
Valor (1191)  6.2.3
Soul Cinders (1906) 9.1.0 
Stygian Ember (1977) 9.1.0
Grateful Offering (1885) 9.0.2
Cataloged Research (1931) 9.1.0
Tower Knowledge (1904) 9.1.0

Redeemed Soul-Kyrian (1863) 9.0.1
Redeemed Soul-Venthyr (1864) 9.0.1
Redeemed Soul-Night Fae (1865) 9.0.1
Redeemed Soul-Necrolord (1866) 9.0.1

**Comment by yoshimo** [comment]
Not sure if sanctum architect 
https://www.wowhead.com/currency=1867/sanctum-architect-kyrian
leads to something useful

**Comment by Loredrin** [comment]
Tried adding these currencies to the "local currencies" section of the code. Followed the same format as what was there already. Mod would not load at all though. Is there somewhere else in the code that needs updated as well when adding these currencies?

**Comment by davidcraig** [comment]
Hi Loredrin, adding to local currencies table is one step, the other part is locales/enUS.lua the L["NAME_{X}"] = "" translations need to be added, although these days it is pretty much just useful for english I don't know if anyone bothers with the translations anymore, but still I kept the enUS file as it's a (lot riskier/lot of work) to remove just for the sake of it. i'm pushing an update now with all of the above currencies except 1867 - unless someone says they're used i'll leave it out for now.

**Comment by davidcraig** [comment]
v1.8.6 pushed with these currencies, tested addon in client on bank alt since I don't have sub.

**Comment by Loredrin** [comment]
Thank you! Love this mod. So much easier to mouse over Titan Panel to see currency amounts on alts with it.
