### ISSUE TITLE
Error message with 10.2.7

### ISSUE THREAD

**Issue by fraerie** [wow-addon/Broker_CurrencyFlow#23]
10x Broker_Currencyflow/Broker_Currencyflow.toc:30 Duplicate File Load Detected. [Broker_Currencyflow/Libs/AceLocale-3.0-6/AceLocale-3.0.xml] first loaded at [Broker_Currencyflow/Broker_Currencyflow.toc:27]

**Comment by davidcraig** [comment]
Fixed in v1.9.0
